monolog:
    handlers:
        main:
            type: group
            members: [dockerlog, console]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        dockerlog:
            type: stream
            path: "php://stderr"
            level: error
            channels: ["!event", "!doctrine"]
