index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      path: /api/docs
      permanent: true

gesdinet_jwt_refresh_token:
  path:       /refresh_token
  controller: gesdinet.jwtrefreshtoken::refresh

authentication_token:
  path: /authentication_token
  methods: ['POST']
