index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
      path: /api/docs
      permanent: true

authentication_token:
  path: /authentication_token
  methods: ['POST']
