monolog:
    handlers:
        main:
            type: group
            members: [dockerlog, console]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        dockerlog:
            type: stream
            path: "php://stderr"
            level: error
            channels: ["!event", "!doctrine"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
