name: Build Docker Image
on:
  create:
    tags:
      - '*'
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Fetching latest tags
        run: echo ::set-env name=CURRENT_TAG::$(echo $GITHUB_REF )
      - name: Publishing PHP Image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ndy40/production
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: server/prod.Dockerfile
          tags: php-${{ env.CURRENT_TAG }}
          cache: true
          buildoptions: "--target server_php"
          buildargs: APP_ENV=prod
          context: server/
      - name: Publishing Nginx Image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ndy40/production
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: server/prod.Dockerfile
          tags: nginx-${{ env.CURRENT_TAG }}
          cache: true
          buildoptions: "--target server_nginx"
          buildargs: APP_ENV=prod
          context: server/
