name: Build Docker Image
on:
  create:
    tags:
      - '*'
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Fetching latest tags
        run: echo ::set-env name=CURRENT_TAG::$(echo $GITHUB_REF | sed 's/.*\///g' )
      - name: Publishing PHP Image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ndy40/production
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: server/prod.Dockerfile
          tags: php-${{ env.CURRENT_TAG }}
          cache: true
          buildoptions: "--target server_php"
          buildargs: APP_ENV=prod
          context: server/
      - name: Publishing Nginx Image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ndy40/production
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: server/prod.Dockerfile
          tags: nginx-${{ env.CURRENT_TAG }}
          cache: true
          buildoptions: "--target server_nginx"
          buildargs: APP_ENV=prod
          context: server/
  deploy-to-server:
    name: Deploy newly built image to server
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Create .env file
        run: |
          echo ${{ secrets.APP_ENV }} | base64 -d | tee .env > /dev/null
          ls -al
          echo ".env file created"
      - name: Update docker-composer file
        run: |
          sed "s/CURRENT_TAG/${{ secrets.CURRENT_TAG }}/g" docker-compose.tmpl > docker-compose.prod.yml
      - name: Add Private SSH KEY to SSH Agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE }}"
      - name: Copy Files to Remote
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml ${{ secrets.SERVER_USER}}@${{ secrets.SERVER_IP }}:${{secrets.DEPLOY_PATH}}
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER}}@${{ secrets.SERVER_IP }} << 'ENDSSH'
            source .env
            cd lsg_app/
            mv docker-compose.prod.yaml docker-compose.yml
            docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker-compose down --rmi all --remove-orphans
            docker-compose up -d
          ENDSSH
